#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v10
# autospec commit: 6fa3d52db448
#
Name     : libajantv2
Version  : 17.0.1
Release  : 1
URL      : https://github.com/aja-video/libajantv2/archive/ntv2_17_0_1/libajantv2-17.0.1.tar.gz
Source0  : https://github.com/aja-video/libajantv2/archive/ntv2_17_0_1/libajantv2-17.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libajantv2-bin = %{version}-%{release}
Requires: libajantv2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : git
BuildRequires : glew-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center">
<a href="https://www.aja.com/">
<img src="aja_logo.svg" alt="AJA Video Systems" width="33%"/>
</a>
</p>

%package bin
Summary: bin components for the libajantv2 package.
Group: Binaries
Requires: libajantv2-license = %{version}-%{release}

%description bin
bin components for the libajantv2 package.


%package dev
Summary: dev components for the libajantv2 package.
Group: Development
Requires: libajantv2-bin = %{version}-%{release}
Provides: libajantv2-devel = %{version}-%{release}
Requires: libajantv2 = %{version}-%{release}

%description dev
dev components for the libajantv2 package.


%package license
Summary: license components for the libajantv2 package.
Group: Default

%description license
license components for the libajantv2 package.


%prep
%setup -q -n libajantv2-ntv2_17_0_1
cd %{_builddir}/libajantv2-ntv2_17_0_1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716927932
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1716927932
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libajantv2
cp %{_builddir}/libajantv2-ntv2_17_0_1/LICENSE %{buildroot}/usr/share/package-licenses/libajantv2/b8f05a1bbe2c79f613b47b1ab5c71c9e8c6067b4 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/libajantv2/.gitignore
/usr/libajantv2/CMakeLists.txt
/usr/libajantv2/ajantv2/CMakeLists.txt
/usr/libajantv2/ajantv2/Makefile
/usr/libajantv2/ajantv2/build/Makefile
/usr/libajantv2/ajantv2/includes/ajaexport.h
/usr/libajantv2/ajantv2/includes/ajatypes.h
/usr/libajantv2/ajantv2/includes/ntv2audiodefines.h
/usr/libajantv2/ajantv2/includes/ntv2devicefeatures.h
/usr/libajantv2/ajantv2/includes/ntv2devicefeatures.hh
/usr/libajantv2/ajantv2/includes/ntv2driverprocamp.h
/usr/libajantv2/ajantv2/includes/ntv2enums.h
/usr/libajantv2/ajantv2/includes/ntv2fixed.h
/usr/libajantv2/ajantv2/includes/ntv2publicinterface.h
/usr/libajantv2/ajantv2/includes/ntv2version.h
/usr/libajantv2/ajantv2/includes/ntv2videodefines.h
/usr/libajantv2/ajantv2/includes/ntv2virtualregisters.h
/usr/libajantv2/ajantv2/includes/ntv2vpidfromspec.h
/usr/libajantv2/ajantv2/src/lin/ntv2linuxpublicinterface.h
/usr/libajantv2/ajantv2/src/targets.mk
/usr/libajantv2/ajantv2/test/CMakeLists.txt
/usr/libajantv2/demos/CMakeLists.txt
/usr/libajantv2/demos/ntv2burn/CMakeLists.txt
/usr/libajantv2/demos/ntv2burn/Makefile
/usr/libajantv2/demos/ntv2burn4kquadrant/CMakeLists.txt
/usr/libajantv2/demos/ntv2burn4kquadrant/Makefile
/usr/libajantv2/demos/ntv2capture/CMakeLists.txt
/usr/libajantv2/demos/ntv2capture/Makefile
/usr/libajantv2/demos/ntv2capture4k/CMakeLists.txt
/usr/libajantv2/demos/ntv2capture4k/Makefile
/usr/libajantv2/demos/ntv2capture8k/CMakeLists.txt
/usr/libajantv2/demos/ntv2capture8k/Makefile
/usr/libajantv2/demos/ntv2dolbycapture/CMakeLists.txt
/usr/libajantv2/demos/ntv2dolbycapture/Makefile
/usr/libajantv2/demos/ntv2dolbyplayer/CMakeLists.txt
/usr/libajantv2/demos/ntv2dolbyplayer/Makefile
/usr/libajantv2/demos/ntv2enumerateboards/CMakeLists.txt
/usr/libajantv2/demos/ntv2enumerateboards/Makefile
/usr/libajantv2/demos/ntv2fieldburn/CMakeLists.txt
/usr/libajantv2/demos/ntv2fieldburn/Makefile
/usr/libajantv2/demos/ntv2hdrsetup/CMakeLists.txt
/usr/libajantv2/demos/ntv2hdrsetup/Makefile
/usr/libajantv2/demos/ntv2konaipj2ksetup/CMakeLists.txt
/usr/libajantv2/demos/ntv2konaipj2ksetup/Makefile
/usr/libajantv2/demos/ntv2konaipjsonsetup/CMakeLists.txt
/usr/libajantv2/demos/ntv2konaipjsonsetup/Makefile
/usr/libajantv2/demos/ntv2konaipjsonsetup/konaipsetup2022_12.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/konaipsetup2022_6_2p2.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/konaipsetup2022_6rx.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/konaipsetup2022_6tx.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/konaipsetup2022_7rx.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/konaipsetup2022_7tx.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/ntv2konaipjsonsetup.pro
/usr/libajantv2/demos/ntv2konaipjsonsetup/t21102rx_2tx.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/t2110_combo-1.json
/usr/libajantv2/demos/ntv2konaipjsonsetup/t2110_combo-2.json
/usr/libajantv2/demos/ntv2llburn/CMakeLists.txt
/usr/libajantv2/demos/ntv2llburn/Makefile
/usr/libajantv2/demos/ntv2outputtestpattern/CMakeLists.txt
/usr/libajantv2/demos/ntv2outputtestpattern/Makefile
/usr/libajantv2/demos/ntv2player/CMakeLists.txt
/usr/libajantv2/demos/ntv2player/Makefile
/usr/libajantv2/demos/ntv2player4k/CMakeLists.txt
/usr/libajantv2/demos/ntv2player4k/Makefile
/usr/libajantv2/demos/ntv2player8k/CMakeLists.txt
/usr/libajantv2/demos/ntv2player8k/Makefile
/usr/libajantv2/demos/ntv2streamplayer/CMakeLists.txt
/usr/libajantv2/demos/ntv2streamplayer/Makefile
/usr/libajantv2/demos/ntv2switchbitfile/CMakeLists.txt
/usr/libajantv2/demos/ntv2switchbitfile/Makefile
/usr/libajantv2/driver/CMakeLists.txt
/usr/libajantv2/driver/configure.mk
/usr/libajantv2/driver/linux/.gitignore
/usr/libajantv2/driver/linux/Makefile
/usr/libajantv2/driver/linux/buildenv.h
/usr/libajantv2/driver/linux/dkms.conf
/usr/libajantv2/driver/linux/driverdbg.h
/usr/libajantv2/driver/linux/fs1wait.h
/usr/libajantv2/driver/linux/ntv2dma.h
/usr/libajantv2/driver/linux/ntv2driver.h
/usr/libajantv2/driver/linux/ntv2driverautocirculate.h
/usr/libajantv2/driver/linux/ntv2driverbigphysarea.h
/usr/libajantv2/driver/linux/ntv2driverdbgmsgctl.h
/usr/libajantv2/driver/linux/ntv2driverstatus.h
/usr/libajantv2/driver/linux/ntv2drivertask.h
/usr/libajantv2/driver/linux/ntv2kona2.h
/usr/libajantv2/driver/linux/ntv2serial.h
/usr/libajantv2/driver/linux/nvidia-ko-to-module-symvers
/usr/libajantv2/driver/linux/registerio.h
/usr/libajantv2/driver/ntv2anc.h
/usr/libajantv2/driver/ntv2audio.h
/usr/libajantv2/driver/ntv2autocirc.h
/usr/libajantv2/driver/ntv2autofunc.h
/usr/libajantv2/driver/ntv2aux.h
/usr/libajantv2/driver/ntv2commonreg.h
/usr/libajantv2/driver/ntv2displayid.h
/usr/libajantv2/driver/ntv2gen2regs.h
/usr/libajantv2/driver/ntv2gen2regs_8a34045.h
/usr/libajantv2/driver/ntv2gen2regs_rc32012a.h
/usr/libajantv2/driver/ntv2genlock.h
/usr/libajantv2/driver/ntv2genlock2.h
/usr/libajantv2/driver/ntv2genregs.h
/usr/libajantv2/driver/ntv2hdmiedid.h
/usr/libajantv2/driver/ntv2hdmiin.h
/usr/libajantv2/driver/ntv2hdmiin4.h
/usr/libajantv2/driver/ntv2hdmiout4.h
/usr/libajantv2/driver/ntv2hin4reg.h
/usr/libajantv2/driver/ntv2hinreg.h
/usr/libajantv2/driver/ntv2hout4reg.h
/usr/libajantv2/driver/ntv2infoframe.h
/usr/libajantv2/driver/ntv2kona.h
/usr/libajantv2/driver/ntv2mcap.h
/usr/libajantv2/driver/ntv2pciconfig.h
/usr/libajantv2/driver/ntv2rp188.h
/usr/libajantv2/driver/ntv2setup.h
/usr/libajantv2/driver/ntv2stream.h
/usr/libajantv2/driver/ntv2system.h
/usr/libajantv2/driver/ntv2video.h
/usr/libajantv2/driver/ntv2videoraster.h
/usr/libajantv2/driver/ntv2videorasterreg.h
/usr/libajantv2/driver/ntv2vpid.h
/usr/libajantv2/driver/ntv2xpt.h
/usr/libajantv2/driver/ntv2xptlookup.h
/usr/libajantv2/driver/sdkversion.mk
/usr/libajantv2/legacy/build/common.mk
/usr/libajantv2/legacy/build/configure.mk
/usr/libajantv2/legacy/build/internal.mk
/usr/libajantv2/legacy/build/qt.mk
/usr/libajantv2/legacy/build/sdkversion.mk
/usr/libajantv2/legacy/build/targets.mk
/usr/libajantv2/plugins/CMakeLists.txt
/usr/libajantv2/tools/CMakeLists.txt
/usr/libajantv2/tools/logreader/CMakeLists.txt
/usr/libajantv2/tools/ntv2firmwareinstaller/CMakeLists.txt
/usr/libajantv2/tools/ntv2firmwareinstaller/Makefile
/usr/libajantv2/tools/ntv2thermo/CMakeLists.txt
/usr/libajantv2/tools/ntv2thermo/Makefile
/usr/libajantv2/tools/pciwhacker/CMakeLists.txt
/usr/libajantv2/tools/pciwhacker/Makefile
/usr/libajantv2/tools/regio/CMakeLists.txt
/usr/libajantv2/tools/regio/Makefile
/usr/libajantv2/tools/supportlog/CMakeLists.txt

%files bin
%defattr(-,root,root,-)
/usr/bin/logreader
/usr/bin/ntv2burn
/usr/bin/ntv2burn4kquadrant
/usr/bin/ntv2capture
/usr/bin/ntv2capture4k
/usr/bin/ntv2capture8k
/usr/bin/ntv2dolbycapture
/usr/bin/ntv2dolbyplayer
/usr/bin/ntv2enumerateboards
/usr/bin/ntv2fieldburn
/usr/bin/ntv2firmwareinstaller
/usr/bin/ntv2hdrsetup
/usr/bin/ntv2konaipj2ksetup
/usr/bin/ntv2konaipjsonsetup
/usr/bin/ntv2llburn
/usr/bin/ntv2outputtestpattern
/usr/bin/ntv2player
/usr/bin/ntv2player4k
/usr/bin/ntv2player8k
/usr/bin/ntv2streamplayer
/usr/bin/ntv2switchbitfile
/usr/bin/ntv2thermo
/usr/bin/pciwhacker
/usr/bin/regio
/usr/bin/supportlog

%files dev
%defattr(-,root,root,-)
/usr/include/libajantv2/ajaanc/includes/ancillarydata.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_cea608.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_cea608_line21.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_cea608_vanc.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_cea708.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_framestatusinfo524D.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_framestatusinfo5251.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_hdr_hdr10.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_hdr_hlg.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_hdr_sdr.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_timecode.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_timecode_atc.h
/usr/include/libajantv2/ajaanc/includes/ancillarydata_timecode_vitc.h
/usr/include/libajantv2/ajaanc/includes/ancillarydatafactory.h
/usr/include/libajantv2/ajaanc/includes/ancillarylist.h
/usr/include/libajantv2/ajabase/common/ajamovingavg.h
/usr/include/libajantv2/ajabase/common/ajarefptr.h
/usr/include/libajantv2/ajabase/common/audioutilities.h
/usr/include/libajantv2/ajabase/common/buffer.h
/usr/include/libajantv2/ajabase/common/bytestream.h
/usr/include/libajantv2/ajabase/common/circularbuffer.h
/usr/include/libajantv2/ajabase/common/cli_utils.h
/usr/include/libajantv2/ajabase/common/commandline.h
/usr/include/libajantv2/ajabase/common/common.h
/usr/include/libajantv2/ajabase/common/dpx_hdr.h
/usr/include/libajantv2/ajabase/common/dpxfileio.h
/usr/include/libajantv2/ajabase/common/export.h
/usr/include/libajantv2/ajabase/common/guid.h
/usr/include/libajantv2/ajabase/common/options_popt.h
/usr/include/libajantv2/ajabase/common/performance.h
/usr/include/libajantv2/ajabase/common/pixelformat.h
/usr/include/libajantv2/ajabase/common/public.h
/usr/include/libajantv2/ajabase/common/rawfile.h
/usr/include/libajantv2/ajabase/common/timebase.h
/usr/include/libajantv2/ajabase/common/timecode.h
/usr/include/libajantv2/ajabase/common/timecodeburn.h
/usr/include/libajantv2/ajabase/common/timer.h
/usr/include/libajantv2/ajabase/common/types.h
/usr/include/libajantv2/ajabase/common/variant.h
/usr/include/libajantv2/ajabase/common/videotypes.h
/usr/include/libajantv2/ajabase/common/videoutilities.h
/usr/include/libajantv2/ajabase/common/wavewriter.h
/usr/include/libajantv2/ajabase/network/ip_socket.h
/usr/include/libajantv2/ajabase/network/tcp_socket.h
/usr/include/libajantv2/ajabase/network/udp_socket.h
/usr/include/libajantv2/ajabase/persistence/persistence.h
/usr/include/libajantv2/ajabase/persistence/sqlite3.h
/usr/include/libajantv2/ajabase/pnp/linux/pnpimpl.h
/usr/include/libajantv2/ajabase/pnp/mac/devicenotifier.h
/usr/include/libajantv2/ajabase/pnp/mac/masterport.h
/usr/include/libajantv2/ajabase/pnp/mac/pnpimpl.h
/usr/include/libajantv2/ajabase/pnp/pnp.h
/usr/include/libajantv2/ajabase/pnp/windows/pnpimpl.h
/usr/include/libajantv2/ajabase/system/atomic.h
/usr/include/libajantv2/ajabase/system/debug.h
/usr/include/libajantv2/ajabase/system/debugshare.h
/usr/include/libajantv2/ajabase/system/diskstatus.h
/usr/include/libajantv2/ajabase/system/event.h
/usr/include/libajantv2/ajabase/system/file_io.h
/usr/include/libajantv2/ajabase/system/info.h
/usr/include/libajantv2/ajabase/system/linux/eventimpl.h
/usr/include/libajantv2/ajabase/system/linux/infoimpl.h
/usr/include/libajantv2/ajabase/system/linux/lockimpl.h
/usr/include/libajantv2/ajabase/system/linux/processimpl.h
/usr/include/libajantv2/ajabase/system/linux/threadimpl.h
/usr/include/libajantv2/ajabase/system/lock.h
/usr/include/libajantv2/ajabase/system/log.h
/usr/include/libajantv2/ajabase/system/mac/eventimpl.h
/usr/include/libajantv2/ajabase/system/mac/infoimpl.h
/usr/include/libajantv2/ajabase/system/mac/lockimpl.h
/usr/include/libajantv2/ajabase/system/mac/processimpl.h
/usr/include/libajantv2/ajabase/system/mac/pthreadsextra.h
/usr/include/libajantv2/ajabase/system/mac/threadimpl.h
/usr/include/libajantv2/ajabase/system/make_unique_shim.h
/usr/include/libajantv2/ajabase/system/memory.h
/usr/include/libajantv2/ajabase/system/process.h
/usr/include/libajantv2/ajabase/system/system.h
/usr/include/libajantv2/ajabase/system/systemtime.h
/usr/include/libajantv2/ajabase/system/thread.h
/usr/include/libajantv2/ajabase/system/windows/eventimpl.h
/usr/include/libajantv2/ajabase/system/windows/infoimpl.h
/usr/include/libajantv2/ajabase/system/windows/lockimpl.h
/usr/include/libajantv2/ajabase/system/windows/processimpl.h
/usr/include/libajantv2/ajabase/system/windows/threadimpl.h
/usr/include/libajantv2/ajantv2/includes/ajaexport.h
/usr/include/libajantv2/ajantv2/includes/ajatypes.h
/usr/include/libajantv2/ajantv2/includes/basemachinecontrol.h
/usr/include/libajantv2/ajantv2/includes/ntv2audiodefines.h
/usr/include/libajantv2/ajantv2/includes/ntv2bft.h
/usr/include/libajantv2/ajantv2/includes/ntv2bitfile.h
/usr/include/libajantv2/ajantv2/includes/ntv2bitfilemanager.h
/usr/include/libajantv2/ajantv2/includes/ntv2card.h
/usr/include/libajantv2/ajantv2/includes/ntv2choosableboard.h
/usr/include/libajantv2/ajantv2/includes/ntv2config2022.h
/usr/include/libajantv2/ajantv2/includes/ntv2config2110.h
/usr/include/libajantv2/ajantv2/includes/ntv2configts2022.h
/usr/include/libajantv2/ajantv2/includes/ntv2cscmatrix.h
/usr/include/libajantv2/ajantv2/includes/ntv2debug.h
/usr/include/libajantv2/ajantv2/includes/ntv2debugmacros.h
/usr/include/libajantv2/ajantv2/includes/ntv2devicefeatures.h
/usr/include/libajantv2/ajantv2/includes/ntv2devicefeatures.hh
/usr/include/libajantv2/ajantv2/includes/ntv2devicescanner.h
/usr/include/libajantv2/ajantv2/includes/ntv2driverinterface.h
/usr/include/libajantv2/ajantv2/includes/ntv2endian.h
/usr/include/libajantv2/ajantv2/includes/ntv2enhancedcsc.h
/usr/include/libajantv2/ajantv2/includes/ntv2enums.h
/usr/include/libajantv2/ajantv2/includes/ntv2fixed.h
/usr/include/libajantv2/ajantv2/includes/ntv2formatdescriptor.h
/usr/include/libajantv2/ajantv2/includes/ntv2konaflashprogram.h
/usr/include/libajantv2/ajantv2/includes/ntv2m31enums.h
/usr/include/libajantv2/ajantv2/includes/ntv2m31publicinterface.h
/usr/include/libajantv2/ajantv2/includes/ntv2mailbox.h
/usr/include/libajantv2/ajantv2/includes/ntv2mbcontroller.h
/usr/include/libajantv2/ajantv2/includes/ntv2mcsfile.h
/usr/include/libajantv2/ajantv2/includes/ntv2nubaccess.h
/usr/include/libajantv2/ajantv2/includes/ntv2nubtypes.h
/usr/include/libajantv2/ajantv2/includes/ntv2publicinterface.h
/usr/include/libajantv2/ajantv2/includes/ntv2registerexpert.h
/usr/include/libajantv2/ajantv2/includes/ntv2registers2022.h
/usr/include/libajantv2/ajantv2/includes/ntv2registers2110.h
/usr/include/libajantv2/ajantv2/includes/ntv2registersmb.h
/usr/include/libajantv2/ajantv2/includes/ntv2resample.h
/usr/include/libajantv2/ajantv2/includes/ntv2routingexpert.h
/usr/include/libajantv2/ajantv2/includes/ntv2rp188.h
/usr/include/libajantv2/ajantv2/includes/ntv2serialcontrol.h
/usr/include/libajantv2/ajantv2/includes/ntv2signalrouter.h
/usr/include/libajantv2/ajantv2/includes/ntv2spiinterface.h
/usr/include/libajantv2/ajantv2/includes/ntv2supportlogger.h
/usr/include/libajantv2/ajantv2/includes/ntv2task.h
/usr/include/libajantv2/ajantv2/includes/ntv2testpatterngen.h
/usr/include/libajantv2/ajantv2/includes/ntv2transcode.h
/usr/include/libajantv2/ajantv2/includes/ntv2tshelper.h
/usr/include/libajantv2/ajantv2/includes/ntv2utf8.h
/usr/include/libajantv2/ajantv2/includes/ntv2utils.h
/usr/include/libajantv2/ajantv2/includes/ntv2version.h
/usr/include/libajantv2/ajantv2/includes/ntv2verticalfilter.h
/usr/include/libajantv2/ajantv2/includes/ntv2videodefines.h
/usr/include/libajantv2/ajantv2/includes/ntv2virtualregisters.h
/usr/include/libajantv2/ajantv2/includes/ntv2vpid.h
/usr/include/libajantv2/ajantv2/includes/ntv2vpidfromspec.h
/usr/include/libajantv2/ajantv2/src/lin/ntv2linuxdriverinterface.h
/usr/include/libajantv2/ajantv2/src/lin/ntv2linuxpublicinterface.h
/usr/include/libajantv2/ajantv2/src/mac/ntv2macdriverinterface.h
/usr/include/libajantv2/ajantv2/src/mac/ntv2macpublicinterface.h
/usr/include/libajantv2/ajantv2/src/win/ntv2windriverinterface.h
/usr/include/libajantv2/ajantv2/src/win/ntv2winpublicinterface.h
/usr/include/libajantv2/ajantv2/utilityfiles/public/ntv2firmwareinstallerthread.h
/usr/include/libajantv2/ajantv2/utilityfiles/public/ntv2hevcfirmwareinstallerthread.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libajantv2/b8f05a1bbe2c79f613b47b1ab5c71c9e8c6067b4
